### ISSUE TITLE
composer extra installer name is wrong

### ISSUE THREAD

**Issue by sams** [froala/wysiwyg-cake2#1]
as per the readme the plugin should be installed _'Plugin/Froala'_ whereas the composer set the plugin to install as _'Plugin/Froala'_

**Comment by stefanneculai** [comment]
Hi Sam! I am not sure what exactly you mean.

**Comment by sams** [comment]
![image](https://cloud.githubusercontent.com/assets/290890/8409846/87f2cc64-1e72-11e5-8859-2194a924b103.png)

The image should made it clear, the second installer setting in composer.json mean the directory wont have to be renamed. Otherwise it could be FroalaEditor (without spaces). I will be forking the plugin I could send a PR for this one minor change :)

**Comment by stefanneculai** [comment]
Done.
