### ISSUE TITLE
can not install with cakephp 3

### ISSUE THREAD

**Issue by yhzhixin** [froala/wysiwyg-cake2#2]
error message:

Generating autoload files

> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
> Script Cake\Composer\Installer\PluginInstaller::postAutoloadDump handling the post-autoload-dump event terminated with an exception

Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]  
  Unable to get primary namespace for package froala/wysiwyg-cake.  
  Ensure you have added proper 'autoload' section to your plugin's config as stated in README on https://github.com/c
  akephp/plugin-installer

**Comment by ThomasNucleus** [comment]
I'm having the same problem. Can this be fixed?

**Comment by stefanneculai** [comment]
@yhzhixin @ThomasNucleus please use https://github.com/froala/wysiwyg-cake for CakePHP 3.
